### ISSUE TITLE
Produce an nubis-skel release

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-skel#6]
Including:
 * tarball/zipfile
 * documentation for new project bootstrapping

**Comment by gozer** [comment]
:clock1: 3h

**Comment by tinnightcap** [comment]
This is now complete. There is a working release tagged at v0.9.0-beta that includes an updated readme with more complete instructions. This not only satisfies the release for this issue but also places us in a ready state for the v0.9.0 release.
